# Paths
DATA_PATH: H:\semseg_fork\semantic-segmentation\data\unreal_images\valid\images\
#SAVE_MODEL_PATH: runs/model_v0.1.pt # Comment this out to autoname models
LOAD_MODEL_PATH: runs_new/model_mobnet_oct30_520.pt

# Image resize variables
IMG_HEIGHT: 520 #526
IMG_WIDTH: 520 #957

# Hyperparameters
NUM_EPOCHS: 10
NUM_MASK_CHANNELS: 4
BATCH_SIZE: 4
LEARNING_RATE: 1e-4
IS_INCEPTION: true
BACKBONE:  # mobilenetv3large, resnet50, resnet101