# Paths
DATA_PATH: data/unreal_images_sample/
SAVE_MODEL_PATH: runs/model_unreal_forest_sep23.pt # Comment this out to autoname models
LOAD_MODEL_PATH: runs/mobilenetv3large_v1.50.pt

# Image resize variables
IMG_HEIGHT: 526
IMG_WIDTH: 957

# Hyperparameters
NUM_EPOCHS: 5
NUM_MASK_CHANNELS: 4
BATCH_SIZE: 4
LEARNING_RATE: 1e-4
IS_INCEPTION: true
BACKBONE: resnet101 # mobilenetv3large, resnet50, resnet101